### ISSUE TITLE
integration with sbt-docker-compose plugin?

### ISSUE THREAD

**Issue by ShahOdin** [marcuslonnberg/sbt-docker#104]
Here is my use case:

- I have an app, which needs a db and a message-broker. I'd like to run `sbt foo` which would run the service along with instances of its dependencies in the background. 

- Currently, I am using the `sbt-docker-compose` to run the dependencies which will expose their network and then I have the choice of running my app whether through sbt or docker. This is because `sbt-docker-compose` doesn't support which involve a build phase.

- Ideally, I'd like to have some sort of integration between `sbt-docker` and `sbt-docker-compose` which would allow me to have a docker compose file with the service itself included so that I would run `sbt dockerComposeUp` and everything runs with all the networking working internally. 

Does anyone else find this use-case useful? If so, how difficult is it to implement?

**Comment by marcuslonnberg** [comment]
I have only limited knowledge about `sbt-docker-compose` so it is hard for me to say how much work it would be to use them together. I would guess you can tie the  different sbt tasks from the plugins together. So that `docker` runs before the `dockerComposeUp` task, or something similar. I hope that helps as a pointed.

Feel free to submit a PR to improve this plugin for better integration.
